name:                dynamic-programming
version:             0.1.0.0
github:              "githubuser/dynamic-programming"
license:             BSD3
author:              "David Wagner"
maintainer:          "wagdav@gmail.com"
copyright:           "2018 David Wagner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/wagdav/dynamic-programming#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers

library:
  source-dirs: src

executables:
  coin:
    main:                Main.hs
    source-dirs:         app/coin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamic-programming
    - criterion

  justify:
    main:                Main.hs
    source-dirs:         app/justify
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamic-programming

tests:
  dynamic-programming-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamic-programming
    - hspec

benchmarks:
  bench-coin:
    main:                Coin.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamic-programming
    - criterion
